<?php
require_once __DIR__ . '/../src/core/bootstrap.php';
if (isset($_SESSION['user_id'])) { header('Location: /dashboard.html'); exit; }
$pageTitle='Create Account — InternBoot'; $asideVariant='register'; $asideTitle='Your first level starts here.'; $asideLead='Create your account, take the Level Assessment Test and climb through the stages. Every stage you clear opens up placement opportunities.';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= htmlspecialchars($pageTitle) ?></title><link rel="icon" href="assets/css/favicon.ico"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,700;12..96,800&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/auth-v3.css"></head>
<body><div class="auth"><?php require __DIR__ . '/../src/core/auth_aside.php'; ?><main class="main"><div class="top"><img class="m-logo" src="assets/css/internboot-official-logo.webp" alt="InternBoot"><p>Already registered? <a href="login.php">Log in</a></p></div>
<div class="shell"><section class="card" id="regCard" data-step="1"><header class="tk"><span class="tk-ico"><svg class="ico"><use href="#i-cap"/></svg></span><div class="tk-t"><b>New candidate</b><small>Level Assessment Test</small></div><ol class="tk-steps" aria-label="Registration steps"><li class="s1 on"><svg class="ico done-i"><use href="#i-check"/></svg><span>Details</span></li><li class="s2"><span>Verify</span></li></ol></header><div class="perf"></div>
<div class="body"><form id="registerForm" novalidate autocomplete="off"><h2 id="regTitle">Create your account</h2><p class="sub" id="regSub">Takes a minute. We'll email you a code to confirm.</p>
<div class="field"><label for="full_name">Full name</label><div class="ctl"><svg class="ico"><use href="#i-user"/></svg><input type="text" id="full_name" name="full_name" placeholder="As you want it on your certificate" autocomplete="name" required></div></div>
<div class="field"><label for="email">Email address</label><div class="ctl"><svg class="ico"><use href="#i-mail"/></svg><input type="email" id="email" name="email" placeholder="you@example.com" autocomplete="email" required></div></div>
<div class="field"><label for="phone">Phone number</label><div class="phone"><select id="country_code" aria-label="Country code"><option value="+91" selected>+91</option><option value="+1">+1</option><option value="+44">+44</option><option value="+61">+61</option><option value="+65">+65</option><option value="+81">+81</option><option value="+971">+971</option><option value="+92">+92</option></select><div class="ctl"><svg class="ico"><use href="#i-phone"/></svg><input type="tel" id="phone" inputmode="numeric" maxlength="15" placeholder="98765 43210" autocomplete="tel-national" required></div></div></div>
<div class="field"><label for="password">Password</label><div class="ctl pw"><svg class="ico"><use href="#i-lock"/></svg><input type="password" id="password" name="password" placeholder="At least 8 characters" autocomplete="new-password" required><button type="button" class="eye ib-toggle-password" data-target="password" aria-label="Show password"><svg class="ico on-i"><use href="#i-eye"/></svg><svg class="ico off"><use href="#i-eyeoff"/></svg></button></div><div class="meter" id="meter" data-s="0"><i></i><i></i><i></i><i></i><span id="meterLabel"></span></div></div>
<div class="field"><label for="confirm_password">Confirm password</label><div class="ctl pw"><svg class="ico"><use href="#i-lock"/></svg><input type="password" id="confirm_password" name="confirm_password" placeholder="Re-enter your password" autocomplete="new-password" required><button type="button" class="eye ib-toggle-password" data-target="confirm_password" aria-label="Show password"><svg class="ico on-i"><use href="#i-eye"/></svg><svg class="ico off"><use href="#i-eyeoff"/></svg></button></div><p class="hint" id="matchHint"></p></div>
<div id="formAlert" class="alert" role="alert"></div><button type="submit" class="btn" id="registerBtn" data-label="Create account">Create account</button><p class="foot">By creating an account you agree to our <a href="terms.html">Terms</a> and <a href="privacy.html">Privacy Policy</a>.</p></form>
<form id="otpForm" class="d-none" novalidate><h2>Check your email</h2><p class="sub">We sent a 6-digit code to</p><div class="otp-mail"><svg class="ico"><use href="#i-mail"/></svg><strong id="otpEmailDisplay"></strong></div><div class="field"><label for="otp1">Verification code</label><div class="otp-boxes" id="otpBoxes"><input type="text" id="otp1" inputmode="numeric" maxlength="6" autocomplete="one-time-code" aria-label="Digit 1"><input type="text" inputmode="numeric" maxlength="1" aria-label="Digit 2"><input type="text" inputmode="numeric" maxlength="1" aria-label="Digit 3"><input type="text" inputmode="numeric" maxlength="1" aria-label="Digit 4"><input type="text" inputmode="numeric" maxlength="1" aria-label="Digit 5"><input type="text" inputmode="numeric" maxlength="1" aria-label="Digit 6"></div><input type="hidden" id="otp_code"></div><div id="otpAlert" class="alert" role="alert"></div><button type="submit" class="btn" id="verifyOtpBtn" data-label="Verify and create account">Verify and create account</button><p class="foot">Didn't get it? <button type="button" class="link" id="resendOtpBtn">Resend code</button><br><button type="button" class="link" id="backToDetails">Use a different email</button></p></form></div></section></div></main></div><script src="assets/js/auth.js"></script></body></html>